[project]
name = "backend"
version = "0.1.0"
description = "Backend API for video compressor"
requires-python = ">=3.14"
dependencies = [
    "hypercorn>=0.18.0",
    "quart>=0.20.0",
    "redis>=7.1.0",
]
